project_id = "lcfzfdjeidinenxcucvj"

[functions.receive-payment-webhook]
verify_jwt = false

[functions.link-user-enrollments]
verify_jwt = false

[functions.manage-google-group]
verify_jwt = false

[functions.sync-google-groups]
verify_jwt = false

[functions.send-class-reminders]
verify_jwt = false

[functions.send-recording-emails]
verify_jwt = false

[functions.send-community-email]
verify_jwt = false
